version: "3"
services:
  web:
    container_name: {{cookiecutter.app_name}}
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
